# Generated by Django 5.0.1 on 2024-02-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Boop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collumn", models.IntegerField()),
                ("row", models.IntegerField()),
                ("booped", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="BoopBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collumns", models.IntegerField()),
                ("rows", models.IntegerField()),
            ],
        ),
    ]
