# Generated by Django 5.0.1 on 2024-02-01 05:30

from django.db import migrations


def initialize_data(apps, schema_editor):
    Boop = apps.get_model('booperapp1', 'Boop')
    # Add initialization logic here
    for i in range(4):
        for j in range(4):
            Boop.objects.create(collumn=i, row=j, booped=False)

class Migration(migrations.Migration):
    dependencies = [
        ("booperapp1", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(initialize_data),
    ]
