# Generated by Django 5.0.1 on 2024-02-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booperapp1", "0003_boop_thisid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="boop",
            old_name="collumn",
            new_name="column",
        ),
        migrations.RenameField(
            model_name="boopboard",
            old_name="collumns",
            new_name="columns",
        ),
        migrations.AddField(
            model_name="boopboard",
            name="myBoops",
            field=models.ManyToManyField(to="booperapp1.boop"),
        ),
    ]
