# Generated by Django 5.0.1 on 2024-02-13 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booperapp1", "0004_rename_collumn_boop_column_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boopboard",
            name="myBoops",
        ),
        migrations.AddField(
            model_name="boop",
            name="boopboard",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="booperapp1.boopboard",
            ),
            preserve_default=False,
        ),
    ]
