# Generated by Django 5.0.1 on 2024-02-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booperapp1", "0005_remove_boopboard_myboops_boop_boopboard"),
    ]

    operations = [
        migrations.AddField(
            model_name="boopboard",
            name="name",
            field=models.CharField(default="Nameless BoopBoard", max_length=100),
        ),
        migrations.AlterField(
            model_name="boopboard",
            name="columns",
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name="boopboard",
            name="rows",
            field=models.IntegerField(default=4),
        ),
    ]
